### ISSUE TITLE
ເຮົາຄວນລຶບຄໍານໍາໜ້າ "ບ້ານ", "ເມືອງ", "ແຂວງ" ອອກດີບໍ່ເພື່ອປະຢັດເນື້ອທີ່ 🗄

### ISSUE THREAD

**Issue by PhouvanhKCSV** [os555/lao-province-district-villages-sql#3]
ສັງເກດເຫັນວ່າຈະມີຄໍານໍາໜ້າ "ບ້ານ", "ເມືອງ", "ແຂວງ" ຢູ່ທຸກຊື່ເລີຍ ເຊິ່ງບໍ່ມີຄວາມຈໍາເປັນຕ້ອງເກັບໄວ້ ເພາະແຕ່ລະອັນກໍແຍກຢູ່ຕາຕະລາງໃຜມັນແລ້ວ, ເວລາເຮົາຈະນໍາໃຊ້ ຫາກມີຄວາມຈໍາເປັນເຮົາກໍພຽງຕໍ່ string ເອົາ ເພື່ອຫຼຸດຜ່ອນການຈັບເກັບຂໍ້ມູນທີ່ບໍ່ຈໍາເປັນ.

ຫາກລຶບ "ບ້ານ", "ເມືອງ", "ແຂວງ" ອອກຈະສາມາດປະຢັດເນື້ອທີ່ສິ້ນເປືອງໄດ້ 116kb (ຈາກ 533kb ເປັນ 417kb).

**Comment by frankxayachack** [comment]
ໜ້າສົນໃຈດຽວຊ່ວຍແກ້ໄຂ #4

**Comment by frankxayachack** [comment]
#4
